apiVersion: v1
kind: Secret
metadata:
  name: glance-secret
  namespace: openstack
stringData:
  TransportUrl: amqp://osp:passw0rd@amq-interconnect.openstack.svc:5672
  DatabasePassword: openstack
  GlanceKeystoneAuthPassword: openstack
