apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstack-proto
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - openstack-proto
  resources:
  - securitycontextconstraints
  verbs:
  - use
